# 生产环境Docker Compose配置
# 用于远程服务器部署，使用外部Redis和MinIO服务

services:
  images-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: images-api:production
    container_name: images-api-service
    ports:
      - "5512:5512"
      - "5513:5513"
    volumes:
      - ./logs:/app/logs:rw
      - ./core:/app/core:ro
      - ./tmp:/app/tmp:rw
      # Google OAuth凭证（生产环境）
      - /home/ecs-user/workspace/google_oauth:/app/google_oauth:ro
    restart: unless-stopped
    
    environment:
      # Python和系统环境
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - LOG_LEVEL=info
      - TZ=Asia/Shanghai
      
      # MinIO配置 - 使用外部jarvis_minio服务
      - MINIO_ENDPOINT=172.22.0.3:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_SECURE=false
      - MINIO_BUCKET_NAME=images
      
      # Redis配置 - 使用外部jarvis_redis服务
      - REDIS_HOST=jarvis_redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      
      # 服务器配置（生产环境）
      - SERVER_BASE_URL=http://8.219.206.213:5512
      - HOST=0.0.0.0
      - PORT=5512
      - MCP_PORT=5513
      
      # 性能配置
      - WORKERS=4
      - MAX_CONNECTIONS=1000
      - KEEPALIVE_TIMEOUT=30
      
      # Google Cloud配置
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google_oauth/qhhl-veo-26fd3f12ace3.json
      - VEO3_PROJECT_ID=qhhl-veo
      - VEO3_LOCATION=us-central1
      - VEO3_STORAGE_BUCKET=veo-output-pub
      - VERTEX_PROJECT_ID=qhhl-veo
      - VERTEX_LOCATION=us-central1
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5512/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    networks:
      - jarvis-v2_default
    
    # 生产环境资源限制（适配2核服务器）
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.8'
        reservations:
          memory: 512M
          cpus: '0.5'
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

networks:
  jarvis-v2_default:
    external: true
    name: jarvis-v2_default