services:
  images-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: images-api-service
    ports:
      - "5512:5512"
      - "5513:5513"
    volumes:
      - ./logs:/app/logs
      - ./core:/app/core
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=info
      - MINIO_ENDPOINT=images-api-minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_SECURE=false
      - MINIO_BUCKET_NAME=images
      - SERVER_BASE_URL=http://8.219.206.213:5512
      - REDIS_HOST=images-api-redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - WORKERS=4
      - MAX_CONNECTIONS=1000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5512/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    external_links:
      - images-api-redis:images-api-redis
      - images-api-minio:images-api-minio
    networks:
      - jarvis-v2_default

networks:
  jarvis-v2_default:
    external: true